<#
.SYNOPSIS
    Adds a visible breadcrumb trail and BreadcrumbList JSON-LD to every article.

.DESCRIPTION
    The 60 category and hub pages already carry both a <div class="breadcrumb">
    trail and BreadcrumbList structured data. None of the 57 articles had either,
    so article results in Google showed a bare URL instead of the

        sportgearfinder.com > Tennis > Best Tennis Strings for Spin

    trail that category pages get. That trail is a CTR lever, and BreadcrumbList
    is also how Google resolves a page's place in the site hierarchy.

    Trail shape:

        Home / <Sport> / <article title>     -> sport hub, e.g. /tennis/
        Home / Articles / <article title>    -> for articles/guides/*, which has
                                                no hub of its own

    The visible trail is inserted between the </section> that closes .art-hero
    and the opening <div class="art-body">, mirroring where category pages put
    theirs. The JSON-LD object is appended to the page's existing ld+json array
    (the one holding the Article node) rather than added as a second <script>,
    so each page keeps exactly one graph.

    Idempotent: a page that already has a BreadcrumbList is skipped, so this can
    be re-run after new articles are generated by build-articles.ps1.

.PARAMETER Apply
    Actually write the changes. Without this the script only reports.

.PARAMETER Filter
    Optional path substring to limit the run, e.g. -Filter tennis

.EXAMPLE
    .\scripts\add-breadcrumbs.ps1
    .\scripts\add-breadcrumbs.ps1 -Apply
#>
[CmdletBinding()]
param(
    [switch]$Apply,
    [string]$Filter = ''
)

Set-StrictMode -Version 2
$ErrorActionPreference = 'Stop'

$RepoRoot = Split-Path -Parent $PSScriptRoot
$Site     = 'https://sportgearfinder.com'

$SportLabel = @{
    tennis = 'Tennis'; gym = 'Gym'; boxing = 'Boxing'; swimming = 'Swimming'
    football = 'Football'; volleyball = 'Volleyball'; pickleball = 'Pickleball'
    'ping-pong' = 'Ping Pong'; badminton = 'Badminton'
}

function HtmlDecode { param([string]$s)
    $s.Replace('&amp;','&').Replace('&lt;','<').Replace('&gt;','>').Replace('&quot;','"').Replace('&#39;',"'")
}
function JEsc { param([string]$s) $s.Replace('\','\\').Replace('"','\"') }
function HEsc { param([string]$s)
    $s.Replace('&','&amp;').Replace('<','&lt;').Replace('>','&gt;')
}

$articles = Get-ChildItem (Join-Path $RepoRoot 'articles') -Recurse -Filter *.html |
            Where-Object { $_.Name -ne 'index.html' }
if ($Filter) { $articles = $articles | Where-Object { $_.FullName -like "*$Filter*" } }

$plan    = @()
$skipped = @()

foreach ($f in $articles) {
    $rel  = $f.FullName.Substring($RepoRoot.Length + 1)
    $text = [System.IO.File]::ReadAllText($f.FullName)

    if ($text -match 'BreadcrumbList') { $skipped += "$rel (already has BreadcrumbList)"; continue }

    # ---- the article's own name: <h1>, minus the <em> emphasis wrapper
    $h1m = [regex]::Match($text, '(?s)<h1>(.*?)</h1>')
    if (-not $h1m.Success) { $skipped += "$rel (no <h1>)"; continue }
    $title = HtmlDecode (($h1m.Groups[1].Value -replace '<[^>]+>', '') -replace '\s+', ' ').Trim()

    # ---- canonical URL: the breadcrumb's own leaf must match it exactly
    $canm = [regex]::Match($text, '<link href="([^"]+)" rel="canonical"/?>')
    if (-not $canm.Success) { $canm = [regex]::Match($text, '<link rel="canonical" href="([^"]+)"/?>') }
    if (-not $canm.Success) { $skipped += "$rel (no canonical)"; continue }
    $canonical = $canm.Groups[1].Value

    # ---- parent tier
    $sportDir = Split-Path (Split-Path $f.FullName -Parent) -Leaf
    if ($SportLabel.ContainsKey($sportDir)) {
        $parentName = $SportLabel[$sportDir]
        $parentUrl  = "$Site/$sportDir/"
        $parentHref = "../../$sportDir/index.html"
    } else {
        $parentName = 'Articles'
        $parentUrl  = "$Site/articles/"
        $parentHref = '../index.html'
    }

    # ---- visible trail, inserted between </section> and <div class="art-body">
    $anchor = [regex]::Match($text, '(?s)</section>(\s*)<div class="art-body">')
    if (-not $anchor.Success) { $skipped += "$rel (no art-hero/art-body anchor)"; continue }
    $gap = $anchor.Groups[1].Value

    $crumbHtml = "</section>`n<div class=`"breadcrumb`">`n" +
                 "<a href=`"../../index.html`">Home</a> / <a href=`"$parentHref`">$parentName</a> / $(HEsc $title)`n" +
                 "</div>$gap<div class=`"art-body`">"

    # ---- JSON-LD: append to whichever block already carries the Article node.
    # Two shapes exist in the wild here: most articles use an array
    # [{Article},{ItemList}], but 14 use a bare {Article} object. Bare objects
    # are promoted to an array so every article ends up with the same shape.
    $ld = $null
    foreach ($m in [regex]::Matches($text, '(?s)<script type="application/ld\+json">(.*?)</script>')) {
        if ($m.Groups[1].Value -match '"@type":\s*"Article"') { $ld = $m.Groups[1].Value; break }
    }
    if (-not $ld) { $skipped += "$rel (no Article ld+json)"; continue }
    $arr = $ld.Trim()

    $crumbLd = '{"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[' +
               '{"@type":"ListItem","position":1,"name":"Home","item":"' + $Site + '"},' +
               '{"@type":"ListItem","position":2,"name":"' + (JEsc $parentName) + '","item":"' + $parentUrl + '"},' +
               '{"@type":"ListItem","position":3,"name":"' + (JEsc $title) + '","item":"' + $canonical + '"}]}'

    if ($arr.StartsWith('[')) {
        # insert before the array's closing bracket
        $newArr = $arr.Substring(0, $arr.Length - 1) + ',' + $crumbLd + ']'
    } else {
        # bare object -> promote to an array holding both nodes
        $newArr = '[' + $arr + ',' + $crumbLd + ']'
    }

    # validate: a page whose structured data would stop parsing is not written
    try { [void](ConvertFrom-Json $newArr) }
    catch { $skipped += "$rel (JSON-LD would not parse: $($_.Exception.Message))"; continue }

    $plan += [pscustomobject]@{
        File      = $rel
        FullPath  = $f.FullName
        Title     = $title
        Parent    = $parentName
        CrumbFrom = $anchor.Value
        CrumbTo   = $crumbHtml
        LdFrom    = $arr
        LdTo      = $newArr
    }
}

# ---------------------------------------------------------------- report
Write-Host ""
if ($plan.Count -eq 0) {
    Write-Host "No articles need breadcrumbs." -ForegroundColor Green
} else {
    Write-Host "$($plan.Count) article(s) to get a breadcrumb trail + BreadcrumbList:" -ForegroundColor Yellow
    Write-Host ""
    foreach ($g in ($plan | Group-Object Parent | Sort-Object Name)) {
        Write-Host ("  Home / {0,-11} {1,2} article(s)" -f $g.Name, $g.Count) -ForegroundColor Gray
    }
    Write-Host ""
    Write-Host "  example: Home / $($plan[0].Parent) / $($plan[0].Title)" -ForegroundColor DarkGray
}
if ($skipped.Count -gt 0) {
    Write-Host ""
    Write-Host "$($skipped.Count) skipped:" -ForegroundColor Magenta
    $skipped | ForEach-Object { Write-Host "  $_" -ForegroundColor DarkGray }
}

Write-Host ""
if (-not $Apply) {
    Write-Host "Report only. Re-run with -Apply to write." -ForegroundColor Cyan
    return
}
if ($plan.Count -eq 0) { return }

# ---------------------------------------------------------------- apply
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
$written = 0
foreach ($p in $plan) {
    $text = [System.IO.File]::ReadAllText($p.FullPath)

    if ($text.IndexOf($p.CrumbFrom) -lt 0) { throw "Anchor drift in $($p.File) (visible trail). Nothing written." }
    if ($text.IndexOf($p.LdFrom)    -lt 0) { throw "Anchor drift in $($p.File) (ld+json). Nothing written." }

    $i = $text.IndexOf($p.CrumbFrom)
    $text = $text.Remove($i, $p.CrumbFrom.Length).Insert($i, $p.CrumbTo)

    $j = $text.IndexOf($p.LdFrom)
    $text = $text.Remove($j, $p.LdFrom.Length).Insert($j, $p.LdTo)

    [System.IO.File]::WriteAllText($p.FullPath, $text, $utf8NoBom)
    $written++
}

Write-Host "Wrote $written file(s)." -ForegroundColor Green
Write-Host "Review with: git diff --stat" -ForegroundColor Cyan
